
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header";
import { HeaderData } from "@/StaticData/HeaderData";
import { Anton } from "next/font/google";
import { a } from "motion/react-client";
import { Bangers } from "next/font/google";
import Footer from "@/sections/Footer";
import { Main } from "next/document";
import MainLayout from "./layouts/MainLayout";

import { shouldShowFooter, shouldShowNavbar } from "@/Utils/LayoutOptions";
import ClientLayoutController from "./workout/components/ClientLayout";
const bangers = Bangers({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bangers",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const anton = Anton({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bangers.variable} ${anton.variable} antialiased`}
      >
       <ClientLayoutController>{children}</ClientLayoutController>
      </body>
    </html>
  );
}
